In [38]:
#business problem - predict the price of banglore house
#using support vector regression 
#we did't use it more

In [4]:
#load libraries
import pandas as pd

In [8]:
#load data
df = pd.read_csv("C:\\Users\\kaushal prasad\\Downloads\\dataset\\bangalore house price prediction OHE-data.csv")

In [6]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [9]:
#split dataset
X = df.drop('price',axis = 1)
y = df['price']

print('shape of X =',X.shape)
print('Shape of y = ',y.shape)

shape of X = (7120, 107)
Shape of y =  (7120,)


In [13]:
#split a data in train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 51)
print('shape of X_train =',X_train.shape)
print('shape of y_train =',y_train.shape)
print('shape of X_test =',X_test.shape)
print('shape of y_test =',y_test.shape)

shape of X_train = (5696, 107)
shape of y_train = (5696,)
shape of X_test = (1424, 107)
shape of y_test = (1424,)


In [14]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [15]:
#train support vector regression model

In [17]:
from sklearn.svm import SVR

In [23]:
#gaussian (radial basis function) kernal
svr_rbf = SVR(kernel = 'rbf')
svr_rbf.fit(X_train, y_train)
svr_rbf.score(X_test, y_test)

0.2063803584082815

In [22]:
#linear function kernal
svr_linear = SVR(kernel = 'linear')
svr_linear.fit(X_train, y_train)
svr_linear.score(X_test, y_test)

0.7962740979067113

In [26]:
#poly function kernal
svr_poly = SVR(kernel = 'poly',degree = 2) #default degree = 3
svr_poly.fit(X_train, y_train)
svr_poly.score(X_test, y_test)

0.18266215678844244

In [28]:
#chosing the best kernal(we predict the value of home and test)

In [29]:
svr_linear = SVR(kernel = 'linear')
svr_linear.fit(X_train, y_train)
svr_linear.score(X_test, y_test)

0.7962740979067113

In [31]:
X_test[0]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [33]:
svr_linear.predict([X_test[0]])

array([86.53631232])

In [35]:
y_pred = svr_linear.predict(X_test)
y_pred

array([ 86.53631232,  33.7037173 , 122.48422547, ...,  26.24020737,
        64.52576739, 176.17735697])

In [36]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [37]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print('MSE= ',mse)
print('RMSE =',rmse)

MSE=  4093.451698511198
RMSE = 63.98008829715069
